### ISSUE TITLE
In Installation and Configuration of git.docx, an error is found

### ISSUE THREAD

**Issue by AjinkyaTaranekar** [Technocolabs/100-Days-of-Code-#1]
Sir, I think there is a mistake in the following lines:-
1.	`git config -global user.name “Yasin”`
2.	`git config -global user.email “technocolabs@gmail.com”`
to respective lines
1.	`git config --global user.name “Yasin”`
2.	`git config --global user.email “technocolabs@gmail.com”`

Thanking you
Ajinkya Taranekar

**Comment by Technocolabs** [comment]
try to make sense brother
git config --global user.name “Yasin”
git config --global user.email “technocolabs@gmail.com”
this is correct

**Comment by AjinkyaTaranekar** [comment]
Thank you for correcting, I will close this issue, to avoid confusion.
